---
- name: restore DB data 
  hosts: tag_Name_RedHat
  remote_user: ec2-user
  # remote_user: user
  tasks:      
  - name: Restore database
    mysql_db:
      name: wordpress
      state: import
      target: /srv/backup/wordpress.sql
    become: true
  - name: restart Mysql
    service: name=mariadb state=restarted
    become: true
     
