---
- name: restore DB data 
  hosts: tag_Env_Demo
  remote_user: root
  # remote_user: user
  sudo: yes
  tasks:      
  - name: Restore database
    mysql_db:
      name: wordpress
      state: import
      target: /srv/backup/wordpress.sql

  - name: restart Mysql
    service: name=mariadb state=restarted
     
