---
- name: restore DB data 
  hosts: tag_Name_RedHat
  tasks:      
  - name: Restore database
    mysql_db:
      name: wordpress
      state: import
      target: /srv/backup/wordpress.sql
      become: yes
  - name: restart Mysql
    service: name=mariadb state=restarted
    become: true
     
