---
- name: Install WordPress, MariaDB, httpd, and PHP
  hosts: tag_Env_Demo
  remote_user: ec2-user
  # remote_user: user
  # sudo: yes

  roles:
#    - referpkg
#    - common
    - mariadb
    - httpd
    - php
    - wordpress
#    - backupDB
