---
- name: Install WordPress, MariaDB, httpd, and PHP
  hosts: tag_Name_RedHat
  remote_user: ec2-user
  # remote_user: user
  become: true
        
  roles:
    - referpkg
    - common
    - mariadb
    - httpd
    - php
    - wordpress
