---
- name: Install WordPress, MariaDB, httpd, and PHP
  hosts: tag_Name_Redhat
  remote_user: ec2-user
  # remote_user: user
  sudo: yes
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        
  roles:
    - referpkg
    - common
    - mariadb
    - httpd
    - php
    - wordpress
