---
- name : SUDO
  hosts: tag_Name_RedHat
  become: true
  

  tasks:
  - name: allow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin yes" state=present

  - name: Restart service sshd
    service:
      name: sshd
      state: restarted

  - name: copy authorized_keys file to root directory
    shell: cp /home/ec2-user/.ssh/authorized_keys /root/.ssh/

  - name : change file ownership
    file:
      path: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: 0600
    become: yes
