---
# sample 

- name: Install NFS-Utils package
  yum: name=nfs-utils state=installed
- name: Update fstab file 
  lineinfile: 
    path: /etc/fstab
    line: "{{ address }}:/{{ volname }} /srv nfs defaults 0 0" 
- name: Verify mount directory exists 
  file: 
    path: /srv
    state: directory
- name: Mount nfs export 
  mount: 
    state: mounted
    path: /srv
    src: "{{ address }}:/{{ volname }}" 
    fstype: nfs
