---
# sample 

- name: Install Dependancy package
  yum: name={{ item }} state=installed
  with_items:
   - nfs-utils
   - libjpeg*
   - libpng*
   - freetype*
   - gd-*
   - gcc
   - gcc-c++
   - gdbm-devel
   - libtermcap-devel

