---
#- name: yum | enable rhui repository
#  yum_repository:
#    name: rhui-REGION-rhel-server-optional
#    enabled: yes
#
#- name: yum | enable rhui repository
#  yum_repository:
#    name: rhui-REGION-rhel-server-optional
#    description: "Red Hat Enterprise Linux Server 7 Optional (RPMs) - $basearch"
#    mirrorlist: "https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/7Server/x86_64/optional/os"
#    failovermethod: priority
#    gpgkey: 
#    gpgcheck: yes
#    enabled: yes
#
#
#- name: Update repository
#  command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
#
- name: Copy the RHUI repository definition
  copy: src=redhat-rhui.repo dest=/etc/yum.repos.d/
#
- name: Copy the RHUI-Client repository definition
  copy: src=redhat-rhui-client-config.repo dest=/etc/yum.repos.d/
#
#- name: Create the GPG key for Apache
#  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg
#
#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg
#
#- name: Create the GPG key for REMI
#  copy: src=RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg
#  
#- name: Install Firewalld
#  yum: name=firewalld state=present

#- name: Firewalld service state
#  service: name=firewalld state=started enabled=yes
